name: build & test
on:
  push:
      branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        llvm_ver: [9,10]
        config:
          - Release
        include:
            - os: ubuntu-18.04
              shell: bash
              cc: /usr/bin/gcc-9
              cxx: /usr/bin/g++-9
              llvm_dir: /usr/lib/llvm-
            - os: ubuntu-20.04
              shell: bash
              cc: /usr/bin/gcc-9
              cxx: /usr/bin/g++-9
              llvm_dir: /usr/lib/llvm-
            - os: macos-latest
              shell: zsh
              cc: /usr/bin/clang
              cxx: /usr/bin/clang++
              llvm_dir: /usr/local/opt/llvm@
            - os: windows-latest
              shell: msys2 {0}
              cmake-generator: -G Ninja
              cc: /usr/bin/clang
              cxx: /usr/bin/clang++
              llvm_dir: /usr/lib/llvm-
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v2
      - if: contains(matrix.os, 'windows')
        name: setup-windows
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel cmake git mingw64/mingw-w64-x86_64-llvm mingw64/mingw-w64-x86_64-libsndfile mingw64/mingw-w64-x86_64-opus
      - if: ${{contains(matrix.os, 'macos')||contains(matrix.os, 'ubuntu') }}
        name: deps-homebrew
        run: |
          brew upgrade
          brew install flex bison libsndfile llvm@${{matrix.llvm_ver}}
      - name: configure
        env:
          LLVM_DIR: ${{ matrix.llvm_dir }}${{ matrix.llvm_ver}}/lib/cmake
        run:
          mkdir build && cd build && cmake ${{ matrix.cmake-generator }}-DCMAKE_BUILD_CONFIG=${{ matrix.config }} -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} ..

      - name: build
        run: cmake --build build --config ${{ matrix.config }}

      - name: test
        run: cd build && ctest --build-config ${{ matrix.config }}
