name: build & test
on:
  push:
      branches:
      - master
      - dev
  pull_request:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      lastmessage: ${{ steps.checkmessage.outputs.lastmessage }}
    steps: 
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - if: contains(github.event_name, 'pull_request')      
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - if: "!contains(github.event_name, 'pull_request')"  
        uses: actions/checkout@v2
      - id: checkmessage
        run: |
          git log --no-merges -1 --oneline
          echo "::set-output name=lastmessage::$(git log --no-merges -1 --oneline)"

  build:
    needs: prebuild
    if: "!contains( needs.prebuild.outputs.lastmessage , '[ci skip]')"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-18.04
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        config:
          - Release
        include:
            # - os: ubuntu-18.04
            #   cxx: /usr/bin/g++-9
            - os: ubuntu-20.04
              cxx: /usr/bin/g++-9
            - os: macos-latest
              cxx: /usr/bin/clang++
            - os: windows-latest
              cxx: g++
    steps:
      - uses: actions/checkout@v2
      - if: contains(matrix.os, 'windows')
        run: | 
          choco install cmake ninja msys2 --no-progress
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64
          C:\tools\msys64\usr\bin\bash -c -l "pacman --noconfirm -S flex bison mingw64/mingw-w64-x86_64-llvm mingw64/mingw-w64-x86_64-libsndfile mingw64/mingw-w64-x86_64-opus"
        shell: cmd
      - if: contains(matrix.os, 'macos')
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install flex bison libsndfile llvm@9 ninja
      - if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install libalsa-ocaml-dev libfl-dev libbison-dev libz-dev libsndfile-dev libopus-dev llvm-10-dev gcc-9 ninja-build
          sudo mkdir /usr/lib/llvm && sudo ln -s /usr/lib/llvm-10** /usr/lib/llvm
      - name: configure
        run:
          cmake . -Bbuild -GNinja -DCMAKE_BUILD_CONFIG=${{ matrix.config }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} 
      - name: build
        run: cmake --build build -j
      - name: test
        run: cd build && ctest
